### ISSUE TITLE
C26 Footprint is incorrect

### ISSUE THREAD

**Issue by emilyanthony4244** [AEFeinstein/Super-2025-Swadge-HW#7]
Did you know there is a difference between nF and uF? I sure did. However, I made a mistake and referenced the 470nF cap footprint for C26, the big boi electrolytic cap. I caught it in a BOM review.

TODO:

1. Update existing or add to Swadge_Parts LCSC C7465562 470**u**F electrolytic capacitor
2. Replace C26 with this part
3. Change location
4. Regenerate mfg data for Elecrow

https://www.lcsc.com/product-detail/Aluminum-Electrolytic-Capacitors-SMD_ROQANG-RVE1A471M0605_C7465562.html

**Comment by AEFeinstein** [comment]
Hmmm, you know what the problem is? You got it set to "n" for nano, when it should be set to "u" for "micro".

[turns the n on the capacitor upside down]

**Comment by AEFeinstein** [comment]
(also move the big boi up so it's nestled between the batteries)

**Comment by emilyanthony4244** [comment]
fixed
